added check fir -lrt to configure

diff --git a/code/trunk/configure b/code/trunk/configure
--- a/code/trunk/configure
+++ b/code/trunk/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os OS ARCH CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP RANLIB ac_ct_RANLIB EGREP CB YACC LEX LEXLIB LEX_OUTPUT_ROOT XSLT M4 PKGCONF GTKLIBS GTKFLAGS LIB_M LIB_SOCKET OPT_O0 OPT_O1 OPT_O2 OPT_O3 OPT_g RCLDFLAGS RCCCFLAGS MKCCFLAGS PDCCFLAGS DEPSFLAG CPPFILE CCMTLINK OSFLAGS LD_DYNAMIC LD_PATH LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os OS ARCH CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP RANLIB ac_ct_RANLIB EGREP CB YACC LEX LEXLIB LEX_OUTPUT_ROOT XSLT M4 PKGCONF GTKLIBS GTKFLAGS LIB_M LIB_SOCKET LIB_RT OPT_O0 OPT_O1 OPT_O2 OPT_O3 OPT_g RCLDFLAGS RCCCFLAGS MKCCFLAGS PDCCFLAGS DEPSFLAG CPPFILE CCMTLINK OSFLAGS LD_DYNAMIC LD_PATH LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4303,6 +4303,80 @@ fi
 fi
 
 
+echo "$as_me:$LINENO: checking for sem_init in -l" >&5
+echo $ECHO_N "checking for sem_init in -l... $ECHO_C" >&6
+if test "${ac_cv_lib__sem_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-l  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char sem_init ();
+int
+main ()
+{
+sem_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib__sem_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib__sem_init=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib__sem_init" >&5
+echo "${ECHO_T}$ac_cv_lib__sem_init" >&6
+if test $ac_cv_lib__sem_init = yes; then
+  LIB_RT=""
+
+else
+  LIB_RT="-lrt"
+
+fi
+
+
+
 echo "$as_me:$LINENO: checking compiler flags" >&5
 echo $ECHO_N "checking compiler flags... $ECHO_C" >&6
 if  test "$GCC" = yes ; then
@@ -5140,6 +5214,7 @@ s,@GTKLIBS@,$GTKLIBS,;t t
 s,@GTKFLAGS@,$GTKFLAGS,;t t
 s,@LIB_M@,$LIB_M,;t t
 s,@LIB_SOCKET@,$LIB_SOCKET,;t t
+s,@LIB_RT@,$LIB_RT,;t t
 s,@OPT_O0@,$OPT_O0,;t t
 s,@OPT_O1@,$OPT_O1,;t t
 s,@OPT_O2@,$OPT_O2,;t t
